### ISSUE TITLE
reset pull down needed for IAC

### ISSUE THREAD

**Issue by ppapadeas** [librespacefoundation/upsat-obc-hardware#15]
- pin 8 (GPIO_184 boot select) should be PULL DOWN with 1MOhm & 100nF

**Comment by zisi** [comment]
It's not necessary to put it, http://www.variscite.com/images/DART-4460-DS_107.pdf page 46 in table 4-21 (System Boot Option Select (internally pulled down)).

We resolve the problem with booting of IAC, giving to it more power (3.3V@0.8A).
