### ISSUE TITLE
Re-design OBC PCB

### ISSUE THREAD

**Issue by ppapadeas** [librespacefoundation/upsat-obc-hardware#6]
On the camera PCB as approved by post-schism meeting. (see upsat-org/issues/20 )

**Comment by ppapadeas** [comment]
PCB dimensional specs can be found here:
https://owncloud.librespacefoundation.org/public.php?service=files&t=1ddd58356de674423263c7dc948a11fb

**Comment by ppapadeas** [comment]
Outer edge dimensional specs could follow this: https://owncloud.librespacefoundation.org/public.php?service=files&t=04128b0a20f9bfa0fad106c8898eb67f

**Comment by zisi** [comment]
Pending review.

**Comment by ykoveos** [comment]
Looks ok!
Just a general comment, in ADCS and OBC we have 10u capacitors after mosfet switches. We must check if voltage drop at the main 3.3V rail is ok when switching on the mosfet .
 In any case when switching on, we can have weak pull down and then active down, or have a few short pulses before permanent LOW, to emulate a soft start.

**Comment by zisi** [comment]
Thank you!! :rocket:
